; This file is project specific and should be checked in to source control.

[mdk]
; This is a programmable block script project.
type=programmableblock

; Toggle trace (on|off) (verbose output)
trace=on

; What type of minification to use (none|trim|stripcomments|lite|full)
minify=full

; Extra options for minification.
minifyextraoptions=none

; A list of files and folder to ignore when creating the script.
ignores=obj/**/*,MDK/**/*,**/*.debug.cs

; A list of allowed namespaces.
namespaces=IngameScript
